particles:
    path: particles/ # Directory with your particle data
    prefix: with_header_halo_lum_ # Prefix of your particle files.
    suffix: .dat # Suffix of your particle files.
    names: # Individual names of your particle files
        - '02'
        #- '05'
        #- '07'
        #- '08'
        #- '09'
        #- '10'
        #- '12'
        #- '14'
        #- '15'
        #- '17'
        #- '20'
    columns: # Header names for age/metallicity/mass columns in your particle files
        age: age # Age
        metallicity: m_h # M_H
        mass: mass # Mass

models:
    # Path to MILES models. DON'T FORGET THE / at the end.
    # Should contain data in following structure (example):
    # MILES_BASTI_UN_baseFe/Mun0.30Zm0.25T00.0300_iTp0.00_baseFe.fits
    path_models: milesdata/models/
    # Path to mass to light ratios
    path_mass_to_light: milesdata/masstolight/
    # Output directory for intermediate data products
    path_output: milesdata/output/

    # Which MILES models would you like to use?
    # All options are listed as comments.
    # Remove the '#' to use.
    isochrone: BaSTI # Padova00
    imftype:
    # un(imodal) or bi(modal)
        - un
        #- bi
    imfslope:
        #- 0.3
        - 0.8
        #- 1.0
        #- 1.3
        #- 1.5
        #- 1.8
        #- 2.0
        #- 2.3
        #- 2.5
        #- 2.8
        #- 3.0
        #- 3.3
    alpha:
        - baseFe
        #- p0.40
        #- p0.00
# Add noise to the spectra?
noise: False # True